# Generated by Django 4.2.11 on 2024-03-31 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
